// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package com.zafin.proto.dummy;

public interface SampleMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dummy.SampleMessage)
    com.google.protobuf.MessageOrBuilder {
}
